### ISSUE TITLE
pip install isn't working.

### ISSUE THREAD

**Issue by thekindlyone** [Corollarium/geograpy2#2]
Downloading/unpacking geograpy2
  Could not find any downloads that satisfy the requirement geograpy2
installing from source isn't working either.

ubuntu 14.04, python 2.7

**Comment by diek** [comment]
I tried as well, Mac yukon, via Python 2.7, same msg.

**Comment by brunobg** [comment]
We're still working on the software. It's not registered on pip yet :|

**Comment by thekindlyone** [comment]
I see. Cool then. All the best :)

**Comment by diek** [comment]
We look forward to seeing it. Aritra and I help admin 3 of the more popular Python FB groups. When you get it registered we will pass along the word.

**Comment by brunobg** [comment]
Oh, thank you, these are good news :) I took a break from this project but I intend to finish it soon. I'll post here when things are ok.

**Comment by diek** [comment]
Sounds good!

**Comment by garrettoca** [comment]
Hi, when do you expect to have geograpy2 registered?

**Comment by brunobg** [comment]
It's still unfinished. The parser is ok, but the code to find the correct cities is not.

**Comment by nolefp** [comment]
yah, I downloaded and then installed  but I keep getting an error saying trees dont have a label attribute... totally dont get it, but what to do...

**Comment by Kolab-Education** [comment]
Hi all, any progress on its release? Just tried to pip install it, but no luck! Will it be registered soon?

**Comment by Cold-A-Muse** [comment]
Yes is this already completed? Unfortunately it is still not available through pip it would be awesome if this would be available any time soon :) !

**Comment by garrettoca** [comment]
Honestly, I wouldn't bother with this, it is very amateurish and incomplete.

**Comment by Cold-A-Muse** [comment]
Haha alright i will look at some other things then ;) !

**Comment by garrettoca** [comment]
What are you trying to achieve, I may be able to advise. G

**Comment by rubychilds** [comment]
@garrettoca I think your comment stating 'very amateurish and incomplete' is very rude and unfair, particularly when this user has spent time doing something open source, whether it be incomplete or not. Instead of moaning in this way that you did, maybe contribute and do a pull request?

**Comment by Cold-A-Muse** [comment]
Currently trying to find all Cities in a piece of text using NLTK's chunker. I am using Geopy atm now but they dont seem to have an option to only find Cities (it finds countries as well) so it is a bit of a hassle.

**Comment by garrettoca** [comment]
Try Yahoo Placemaker

**Comment by garrettoca** [comment]
Unfortunately, publishing poor products costs other people time and money
investigating. It's the suede of FOS s/w. G

**Comment by rubychilds** [comment]
@garrettoca But by OS a project, you save the company having to build one themselves or using proprietary software at a cost. Hence you actually owe anyone willing to OS anything they've worked on a great deal. Try and appreciate people's efforts more rather than this feeling of entitlement that you're showing

**Comment by garrettoca** [comment]
Nobody Is entitled to gratitude for poor work except in la-la land where
everyone is better than average!

**Comment by brunobg** [comment]
This project is not finished and there are messages here stating this. It's why it's not in pip. I appreciate your comments @rubychilds, thank you.
@garrettoca I'd be very pleased to accept your PR to fix what is left to do instead of "saying I'm not paying for it or helping and it doesn't work."

**Comment by MrJarnould** [comment]
Any updates?

**Comment by rocksailor** [comment]
can anyone suggest me good alternative for geograpy, geograpy2 not there yet i guess. 
I need to extract countries and cities names out of a few million text rows.
Tried GeoText, not giving good results.
Any help is appreciated.

**Comment by scottwernervt** [comment]
@rocksailor You can install [nltk](http://www.nltk.org/) and just copy and paste the applicable functions:

    def named_entities(self):
        # word_tokenize should work well for most non-CJK languages
        text = nltk.word_tokenize(self.text)
        
        # TODO: this works only for english. Stanford's pos tagger supports
        # more languages
        # http://www.nltk.org/api/nltk.tag.html#module-nltk.tag.stanford
        # http://stackoverflow.com/questions/1639855/pos-tagging-in-german
        # PT corpus http://aelius.sourceforge.net/manual.html
        # 
        pos_tag = nltk.pos_tag(text)
        
        nes = nltk.ne_chunk(pos_tag)
        return nes
        

    def find_entities(self):
        """Parse text and tokenize it.
        """
        nes = self.named_entities()
        for ne in nes:
            if type(ne) is nltk.tree.Tree:
                if ne.label() in ['GPE', 'PERSON', 'ORGANIZATION']:
                    self.places.append(u' '.join([i[0] for i in ne.leaves()]))

**Comment by JavierTSalas** [comment]
@scottwernervt Where do those functions go? Where do I see the 'output'?

**Comment by scottwernervt** [comment]
@JavierTSalas I copied those class instance methods from https://github.com/Corollarium/geograpy2/blob/master/geograpy2/extraction.py. So just install `nltk` and do not bother with `geograpy2`. Sample could for finding named entities would be:

```python
import nltk

def named_entities(text):
    # word_tokenize should work well for most non-CJK languages
    words = nltk.word_tokenize(text)
    
    # TODO: this works only for english. Stanford's pos tagger supports
    # more languages
    # http://www.nltk.org/api/nltk.tag.html#module-nltk.tag.stanford
    # http://stackoverflow.com/questions/1639855/pos-tagging-in-german
    # PT corpus http://aelius.sourceforge.net/manual.html
    # 
    pos_tag = nltk.pos_tag(words)
    
    nes = nltk.ne_chunk(pos_tag)
    return nes
    

def find_entities(text):
    """Parse text and tokenize it.
    """
    nes = named_entities(text)

    places = []
    for ne in nes:
        if type(ne) is nltk.tree.Tree:
            if ne.label() in ['GPE', 'PERSON', 'ORGANIZATION']:
                places.append(u' '.join([i[0] for i in ne.leaves()]))

    return places


locations = find_entities('I work at GitHub which is located in San Francisco, California.')
```

**Comment by muffincode** [comment]
This didn't work for me :(
I ended up using https://pypi.org/project/geotext/

**Comment by naspuka** [comment]
plz I am unable to write to database...
Traceback (most recent call last):
  File "geo.py", line 25, in <module>
    pc= PlaceContext(e.places)
  File "/usr/local/lib/python3.6/dist-packages/geograpy3/places.py", line 28, in __init__
    self.conn = sqlite3.connect(db_file)
sqlite3.OperationalError: unable to open database file
